spring:
  config:
    activate:
      on-profile: local
    import: application.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      repositories:
        enabled: false

oauth2:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_SECRET_KEY}
  redirect-uri: ${REDIRECT_URI}
