spring:
  config:
    activate:
      on-profile: dev
    import: application.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PW_DEV}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST_DEV}
      repositories:
        enabled: false

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-name: kakao
#            client-id: ${KAKAO_CLIENT_ID_DEV}
#            client-secret: ${KAKAO_SECRET_KEY_DEV}
#            redirect-uri: ${REDIRECT_URL_DEV}
#            authorization-grant-type: authorization_code
#            scope:
#              - name
#              - email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
